# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_isda', [dirname(__file__)])
        except ImportError:
            import _isda
            return _isda
        if fp is not None:
            try:
                _mod = imp.load_module('_isda', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _isda = swig_import_helper()
    del swig_import_helper
else:
    import _isda
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.