from distutils.core import setup, Extension

#https://gist.github.com/taochenshh/b53ce0f54fea5b2204908100d0e566fa
#https://gist.github.com/auth/github?return_to=https%3A%2F%2Fgist.github.com%2Ftaochenshh%2Fb53ce0f54fea5b2204908100d0e566fa

module1 = Extension('_isda',
                    include_dirs = ['C:\\Users\\bakera\\AppData\\Local\\Programs\\Python\\Python37\\include'],
                    library_dirs = ['C:\\Users\\bakera\\AppData\\Local\\Programs\\Python\\Python37\\libs'],
                    sources = ['isda/example.c', 
                    'isda/main.c',
                    'isda/busday.c',
                    'isda/cdsbootstrap.c',
                    'isda/cdsone.c',
                    'isda/cerror.c',
                    'isda/cfileio.c',
                    'isda/cxzerocurve.c', 
                    'isda/cxbsearch.c',
                    'isda/defaulted.c',
                    'isda/tcurve.c',
                    'isda/version.c',
                    'isda/zerocurve.c',
                    'isda/cmemory.c',
                    'isda/cx.c',
                    'isda/interpc.c',
                    'isda/gtozc.c', 
                    'isda/zcall.c',
                    'isda/bsearch.c', 
                    'isda/cfinanci.cpp',
                    'isda/buscache.c',
                    'isda/dtlist.c',
                    'isda/dateconv.c',
                    'isda/rtbrent.c',
                    'isda/zcswap.c',
                    'isda/schedule.c',
                    'isda/streamcf.c',
                    'isda/zcswdate.c',
                    'isda/badday.c',
                    'isda/feeleg.c',
                    'isda/cds.c',
                    'isda/ldate.c',
                    'isda/date_sup.c',
                    'isda/zcswutil.c',
                    'isda/yearfrac.c',
                    'isda/strutil.c',
                    'isda/lintrp1.c',
                    'isda/datelist.c',
                    'isda/lscanf.c',
                    'isda/timeline.c', 
                    'isda/cxdatelist.c',
                    'isda/convert.c', 
                    'isda/stub.c', 
                    'isda/cashflow.c',
                    'isda/contingentleg.c',
                    'isda/zr2coup.c',
                    'isda/lprintf.c',
                    'isda/fltrate.c', 
                    'isda/zr2fwd.c', 
                    'isda/dateadj.c', 'isda/isda.cpp', 'isda/isda_wrap.cxx'])

setup (name = 'isda',
       version = '1.0',
       author='Alexander Baker',
       author_email='baker.alexander@gmail.com',
       description = 'This is a demo package',
       #ext_package='isda',
       #py_modules=['isda'],
       packages=[
            'isda'
            ],
       keywords="credit analytics",
       ext_modules = [module1])
